name: 部署

#推送事件触发
on:
  push:
    branches:
      - master

jobs:
  build:
    name: 部署账本

    # 权限
    permissions:
      contents: write
      packages: write

    # 选择系统运行
    runs-on: ubuntu-latest
    #步骤运行命令
    steps:
      - name: 拉取仓库 # -name让github知道这个步骤的名字
        # 必须使用这个命令才行
        uses: actions/checkout@v4

      - name: 编译构建
        run: |
          cd ${{ github.workspace }}/
          ls
          npm install 
          npm run build

      - name: 上传项目
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub 页面
        id: deployment
        uses: actions/deploy-pages@v4